### PR TITLE
docs: add code review section to contributing.md

### LINKED ISSUE #82: Add Code Review to Contributing.md
- Add a "Code Reviews" section on CONTRIBUTING.md
- Put the following under the header:
> If you can, please look at open PRs and review them. Give feedback and help us merge these PRs much faster! If you don't know how, Github has some great [information on how to review a Pull Request](https://help.github.com/articles/about-pull-request-reviews/).
- Link the header in the Contributing.md Table of Contents
- Add a link to the README.md file: [Review Pull Requests]("CONTRIBUTING.md#Code-Reviews") under "Contributing Section"

### PR DESCRIPTION
**Pull request by omegamendes**
Fixes #82

### Checklist
- [v] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [v] I have read the [Contribution Guide] and my PR follows them.
- [v] I updated my branch with the master branch.
- [v] I have added tests that prove my fix is effective or that my feature works
- [v] I have added necessary documentation about the functionality in the appropriate .md file
- [v] I have added in line documentation to the code I modified

### Short description of what this PR does:
Add the code review section into contributin.md file

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=88) <br/>All committers have signed the CLA.

**Comment by thinkingserious** [comment]
@omegamendes

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by omegamendes** [comment]
Didn't check it before november 3rd... And did not get any notifications... srry about that

**Review by childish-sambino — APPROVED** [review]

**Comment by childish-sambino** [comment]
Merged: https://github.com/sendgrid/java-http-client/commit/4d10515774925edb5ff6728537cbd23a919b127a

**Pull request closed without merging**
