### PR TITLE
Add Code Review to Contributing.md 

### LINKED ISSUE #82: Add Code Review to Contributing.md
- Add a "Code Reviews" section on CONTRIBUTING.md
- Put the following under the header:
> If you can, please look at open PRs and review them. Give feedback and help us merge these PRs much faster! If you don't know how, Github has some great [information on how to review a Pull Request](https://help.github.com/articles/about-pull-request-reviews/).
- Link the header in the Contributing.md Table of Contents
- Add a link to the README.md file: [Review Pull Requests]("CONTRIBUTING.md#Code-Reviews") under "Contributing Section"

### PR DESCRIPTION
**Pull request by JyotsnaC**
# Fixes #82 # 

### Checklist
- [ ] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Mentions how to do do code review
- Update at both at Contributing and Readme

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=84) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=84) before we can accept your contribution.<br/>**10** out of **14** committers have signed the CLA.<br/><br/>:white_check_mark: twistedpair<br/>:white_check_mark: mptap<br/>:white_check_mark: mbernier<br/>:white_check_mark: thinkingserious<br/>:white_check_mark: skshelar<br/>:white_check_mark: JyotsnaC<br/>:white_check_mark: kazoni<br/>:white_check_mark: rohitdaryanani<br/>:white_check_mark: bhavin192<br/>:white_check_mark: pushkyn<br/>:x: Matt Bernier<br/>:x: diegorramos<br/>:x: luiscobits<br/>:x: Jyotsna Chatradhi<br/><hr/>**Matt Bernier, Jyotsna Chatradhi** seem not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/java-http-client?pullRequest=84) it.</sub>

**Comment by thinkingserious** [comment]
@JyotsnaC

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by JyotsnaC** [comment]
@mbernier and @thinkingserious CLA has been signed

**Comment by thinkingserious** [comment]
Hi @JyotsnaC,

The CLA is not being processed, because the PR was made from an account with the username "Jyotsna Chatradhi". Could you please update the author information on your commit?

Thanks!

With Best Regards,

Elmer

**Pull request closed without merging**
