### PR TITLE
Added Code of Conduct to root of repo

### LINKED ISSUE #31: Add a Code Of Conduct
Add a file to the root of this repo called CODE_OF_CONDUCT.md, with the content from the [same file in our docs repo](https://github.com/sendgrid/docs/pull/3048).

### PR DESCRIPTION
**Pull request by keyaa**
Edit by @mbernier:
closes #31

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=32) <br/>All committers have signed the CLA.

**Comment by keyaa** [comment]
Sorry, I can't figure out what to do in order to get the Travis build to pass

**Review by mbernier — APPROVED** [review]

**Comment by thinkingserious** [comment]
Solved by https://github.com/sendgrid/java-http-client/pull/33

**Comment by keyaa** [comment]
both #32 and #33 got closed...?

**Comment by thinkingserious** [comment]
Hi @keyaa,

It looks like @nightrainlily originally grabbed this one and then her PR was mistakenly closed. I am re-opening and merging.

I hope you will still consider contributing to [hacktoberfest](https://sendgrid.com/blog/announcing-hacktoberfest-2017/) :)

**Comment by nightrainlily** [comment]
@thinkingserious thank you! let me know if you need anything else from me.

**Comment by thinkingserious** [comment]
Hi @nightrainlily,

It looks like the formatting is broken on your PR, could you [please double check](https://github.com/nightrainlily/java-http-client/blob/a048c0d60d18029d6f66c34a995a468e7f4e5fdd/CODE_OF_CONDUCT.md).

Thanks!

Elmer

**Comment by nightrainlily** [comment]
@thinkingserious should be fixed now ! sorry

**Pull request closed without merging**
