### PR TITLE
feat: Add close method to Client

### PR DESCRIPTION
**Pull request by tsuyoshizawa**
`Client` class closes http client by `finalize` method.
However, the method is not promised to be called.

The class should have `close` method to call closing http client expressly.
In additional, we shouldn't call `finalize` method expressly if we want to close the client.

`Closeable` interface supports `try-with-resources Statement`.
https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=34) <br/>All committers have signed the CLA.

**Comment by thinkingserious** [comment]
Thank you @tsuyoshizawa!

Would you mind [signing our CLA](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=34) so that we may merge your work? It's just a quick web form.

With Best Regards,

Elmer

**Comment by tsuyoshizawa** [comment]
@thinkingserious I signed the CLA.

**Review by andy-trimble — APPROVED** [review]

**Comment by andy-trimble** [comment]
LGTM

**Comment by mbernier** [comment]
@tsuyoshizawa

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by thinkingserious** [comment]
Hello @tsuyoshizawa,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
