### PR TITLE
Fix charset: Use "UTF-8" charset instead of default "ISO-8859-1"

### PR DESCRIPTION
**Pull request by DanailMinchev**
See: https://github.com/sendgrid/java-http-client/issues/4

### CODE REVIEW

**Comment by thinkingserious** [comment]
Thanks @DanailMinchev!

Could you please sign our CLA so we can get this merged? https://github.com/sendgrid/java-http-client/blob/master/CONTRIBUTING.md#cla

**Comment by DanailMinchev** [comment]
@thinkingserious 

I have sent you the signed pdf to dx@sendgrid.com

Thank you!

**Comment by thinkingserious** [comment]
@DanailMinchev please reach out to us at dx@sendgrid.com with your T-shirt size and mailing address so we can send you some swag.

**Comment by DanailMinchev** [comment]
Ok :smile: - we should thank @wujie8x8 and @toran414 for issue details

Thanks for merging that!

**Comment by thinkingserious** [comment]
@wujie8x8 and @toran414,

Same offer applies to you. Please send your T-shirt size and mailing address so we can send you some swag :)

**Comment by wujie8x8** [comment]
Thank you for the new version.

Jie

**Comment by wujie8x8** [comment]
Hi, Elmer.

My T-shirt size is s (small) and My address is :
 1540 southwest expy. #154
san jose , ca, 95126

Thank you.

Jie

**Comment by thinkingserious** [comment]
@wujie8x8 the smallest size we have is M, but hopefully that will work. Thanks!

**Pull request merged**
