### PR TITLE
test commit

### PR DESCRIPTION
**Pull request by ayushkalani**
Test for this issue TravisCI failing with bad JAVA_HOME env var #28

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=29) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/java-http-client?pullRequest=29) it.</sub>

**Comment by ayushkalani** [comment]
We need to check this out 
https://github.com/travis-ci/travis-ci/issues/7019
https://github.com/travis-ci/travis-ci/issues/7884

**Comment by mbernier** [comment]
@thinkingserious according to the second link from @ayushkalani, it looks like Travis has marked this as a wontfix for oraclejdk7 because Oracle has decided not to support this build see [this comment](https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879)

Should we just remove the `oraclejdk7` dependency in travis.yml?

**Comment by thinkingserious** [comment]
@mbernier,

Yes, and merged: https://github.com/sendgrid/java-http-client/pull/35

**Pull request closed without merging**
