### PR TITLE
Improve Error Handling #10

### PR DESCRIPTION
**Pull request by shuron**
This should improve error handling.
New SendGridResponseHandler was introduced, that ist capable to parse body even on http response status >300.

Also small refactoring of same code.

### CODE REVIEW

**Comment by thinkingserious** [comment]
You are awesome @shuron!

Could you please submit a CLA so we can merge this? https://github.com/sendgrid/java-http-client/blob/master/CONTRIBUTING.md#cla

Thanks!

**Comment by thinkingserious** [comment]
Looks like we will need a CLA from @aholbreich too.

**Comment by aholbreich** [comment]
You shouuld have them for @shuron and @aholbreich in the mean time.

**Comment by thinkingserious** [comment]
Hello @aholbreich,

I have had a chance to review the pull request. 

Could you please provide a usage example? Ideally, here: https://github.com/sendgrid/java-http-client/blob/master/examples/Example.java

Thank you!

**Comment by aholbreich** [comment]
The whole Pool request does not change API behavour of the any call off:

```
response = client.api(request);
```

it only improve the situation with verbosity of response body responses with http eror codey >=300.

I didn't wanted to break any API behaviour with this pull request, so at the end only the Exception Message is more verbouse now and containes body by chance it was send within your backend API response. e.g.

> Request returned status Code 400 Body: XYZ is not accepted for being longer than ABC.

So examples applicable unchnaged.

**Pull request merged**
