### PR TITLE
Make response have private variables 12

### PR DESCRIPTION
**Pull request by diegoc-am**

### CODE REVIEW

**Comment by thinkingserious** [comment]
This looks great @belfazt!

Please take a moment to sign our CLA so we can merge your changes: https://github.com/sendgrid/java-http-client/blob/master/CONTRIBUTING.md#cla

**Comment by diegoc-am** [comment]
Just sent a mail

**Comment by diegoc-am** [comment]
Is this going to be merged?

**Comment by thinkingserious** [comment]
@belfazt,

This pull request is currently in our backlog to review for merge. Thanks!

**Pull request merged**
