### PR TITLE
fix: No longer throwing IOExceptions on non 2xx response codes.

### PR DESCRIPTION
**Pull request by andy-trimble**
This fixes issues https://github.com/sendgrid/sendgrid-java/issues/184 and https://github.com/sendgrid/sendgrid-java/issues/212. This was done as part of issue https://github.com/sendgrid/sendgrid-java/issues/221.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=36) <br/>All committers have signed the CLA.

**Comment by mbernier** [comment]
This last merge should fix the build issues.

**Comment by thinkingserious** [comment]
Hello @andy-trimble,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Comment by jmayday** [comment]
Hi. Thanks for your work @andy-trimble 
When this will be released? This change is only on master, not available on newest version of java-http-client (which is 4.2.0)
BTW. Shouldn't the sendgrid-java be updated to use java-http-client 4.2.0 and not 4.1.0?

**Pull request merged**
