### PR TITLE
Fix Response Charset to UTF-8.

### PR DESCRIPTION
**Pull request by kikutaro**
patch for issue #6

### CODE REVIEW

**Comment by thinkingserious** [comment]
This is awesome, thanks! We have this on our backlog to be merged.

Also, please email us at dx@sendgrid.com with your T-shirt size and mailing address so we can send you some swag :)

**Comment by kikutaro** [comment]
Hi @thinkingserious , I sent email :) Thanks!

**Comment by thinkingserious** [comment]
Hello @kikutaro,

I ran into an issue when trying to run the Example. On [this line](https://github.com/sendgrid/java-http-client/blob/master/examples/Example.java#L109), I get:

``` bash
Exception in thread "main" java.lang.IllegalArgumentException: Entity may not be null
    at org.apache.http.util.Args.notNull(Args.java:54)
    at org.apache.http.util.EntityUtils.toString(EntityUtils.java:214)
    at com.sendgrid.Client.getResponse(Client.java:138)
    at com.sendgrid.Client.delete(Client.java:344)
    at com.sendgrid.Client.api(Client.java:375)
    at Example.main(Example.java:109)
```

I'm thinking we just need a null check before we call `EntityUtils`.

**Comment by kikutaro** [comment]
Oh, okay. Sorry for that I didn't check the example. I only focus test code.
I'll check the case soon. Thanks.

**Comment by kikutaro** [comment]
Hi @thinkingserious,

I added null check. Thanks.

**Comment by thinkingserious** [comment]
Awesome, thanks!

**Comment by thinkingserious** [comment]
@kikutaro,

Could you please update your branch against the latest version? https://github.com/sendgrid/java-http-client/releases/tag/v2.3.3

I'd like to merge your branch next. Thanks!

**Comment by kikutaro** [comment]
I tried it. Sorry that I'm pretty new this pattern merge for me...
If you have any issue on my pull request, please let me know. Thanks.

**Pull request merged**
