### PR TITLE
fix of #28

### PR DESCRIPTION
**Pull request by maxymshg**
Remove oraclejdk7 from .travis.yml as Travis does not support it anymore

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=35) <br/>All committers have signed the CLA.

**Comment by maxymshg** [comment]
For details: https://github.com/travis-ci/travis-ci/issues/7884#issuecomment-308451879

**Comment by maxymshg** [comment]
Related to #28

**Comment by maxymshg** [comment]
About SSL issue, maybe we should do something similar as spock: https://github.com/spockframework/spock/commit/722106bc519ac05ecf2266c71dddb1dac4d6a0fc

**Comment by thinkingserious** [comment]
Hello @maxymshg,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
