### PR TITLE
feat: Allow setting both `apache http client` and `test` parameters

### PR DESCRIPTION
**Pull request by maximn**
#21

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=22) <br/>All committers have signed the CLA.

**Comment by maximn** [comment]
@thinkingserious Hi, do you have any ETA to merge this?

**Comment by thinkingserious** [comment]
Hello @maximn,

No ETA yet, but generally issues gain priority in our backlog with additional +1's or a PR. When we receive a PR, that provides the biggest jump in priority.

However, we are currently working an [upgrade to the library](https://github.com/sendgrid/sendgrid-java/issues/219) and before I start coding that, I will try to clear out any outstanding PRs. I will begin work on the refactor when I get at least 3 thumbs up on it. If you have a moment, I would greatly appreciate [your feedback](https://github.com/sendgrid/sendgrid-java/issues/219).

With Best Regards,

Elmer

**Comment by maximn** [comment]
Hi, there're few thumbs up now. 

This is a very simple and backward compatible change. Please have a look.

The problem is that currently we can't set up the http client that we use to send to SendGrid. This will help us a lot.

**Comment by thinkingserious** [comment]
Thank you for the clarification!

I just need one more thumbs up on the refactor, I'm hoping that will happen this week.

**Comment by maximn** [comment]
There're quite a few thumbs. Do you have an ETA?

**Review by andy-trimble — APPROVED** [review]

**Comment by andy-trimble** [comment]
LGTM

**Comment by amitanafy** [comment]
Hi, do you have any ETA to merge this?

**Comment by thinkingserious** [comment]
Hello @maximn,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
