### PR TITLE
docs: Typos in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by rkaranam**
While I was reading the CONTRIBUTING section to learn how to contribute, I stumbled upon these typos and broken links. Hope this helps!

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=59) <br/>All committers have signed the CLA.

**Comment by mbernier** [comment]
Thank you for these changes! As soon as you sign the CLA we can get it merged in

**Comment by rkaranam** [comment]
@mbernier Signed the CLA

**Comment by mbernier** [comment]
This is my favorite kind of PR. Thank you for noticing AND fixing this!

**Comment by thinkingserious** [comment]
Hello @rkaranam,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
