### PR TITLE
Java 7 support in gradle being depreciated

### PR DESCRIPTION
**Pull request by diegorramos**

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/java-http-client?pullRequest=46) <br/>All committers have signed the CLA.

**Comment by mbernier** [comment]
@Polovinsky Do you have a link to info on Java7 support in gradle being deprecated?

**Comment by thinkingserious** [comment]
Hello @Polovinsky,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Comment by diegorramos** [comment]
You're welcome, it's very nice to be able to help!

**Pull request merged**
